apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "x-metrics.fullname" . }}-leader-election
  namespace: {{ include "x-metrics.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "x-metrics.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "x-metrics.serviceAccountName" . }}
  namespace: {{ include "x-metrics.namespace" . }}
